<a href="https://colab.research.google.com/github/mks2607/Data_Scientist/blob/mks2607/Company.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_dividend = pd.read_csv('/content/Companies_ranked_by_Dividend_Yield.csv')
df_eaning = pd.read_csv('/content/Companies_ranked_by_Earnings.csv')
df_market = pd.read_csv('/content/Companies_ranked_by_Market_Cap.csv')
df_p_e_ratio = pd.read_csv('/content/Companies_ranked_by_P_E_ratio.csv')
df_revenue = pd.read_csv('/content/Companies_ranked_by_Revenue.csv')

In [3]:
df_revenue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9912 entries, 0 to 9911
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Rank         9912 non-null   int64
 1   Name         9912 non-null   object
 2   Symbol       9911 non-null   object
 3   revenue_ttm  9912 non-null   int64
 4   price (GBP)  9912 non-null   float64
 5   country      9910 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 464.8+ KB

In [4]:
df_p_e_ratio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9912 entries, 0 to 9911
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          9912 non-null   int64
 1   Name          9912 non-null   object
 2   Symbol        9911 non-null   object
 3   pe_ratio_ttm  9912 non-null   float64
 4   price (GBP)   9912 non-null   float64
 5   country       9910 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 464.8+ KB

In [5]:
df_dividend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9912 entries, 0 to 9911
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                9912 non-null   int64
 1   Name                9912 non-null   object
 2   Symbol              9911 non-null   object
 3   dividend_yield_ttm  9912 non-null   float64
 4   price (GBP)         9912 non-null   float64
 5   country             9910 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 464.8+ KB

In [6]:
df_eaning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9912 entries, 0 to 9911
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          9912 non-null   int64
 1   Name          9912 non-null   object
 2   Symbol        9911 non-null   object
 3   earnings_ttm  9912 non-null   float64
 4   price (GBP)   9912 non-null   float64
 5   country       9910 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 464.8+ KB

In [7]:
df_market.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9912 entries, 0 to 9911
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Rank         9912 non-null   int64
 1   Name         9912 non-null   object
 2   Symbol       9911 non-null   object
 3   marketcap    9912 non-null   float64
 4   price (GBP)  9912 non-null   float64
 5   country      9910 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 464.8+ KB

In [11]:
df_dividend.head(3)

,Rank,Name,Symbol,dividend_yield_ttm,price (GBP),country
0,1,LianBio,LIAN,300940.0,0.243065,United States
1,2,Richter Gedeon,RIG2.F,150430.0,23.726825,Hungary
2,3,Delek Group,DLEKG.TA,117114.0,87.735884,Israel

In [10]:
df_market.head(3)

   Rank       Name Symbol     marketcap  price (GBP)        country
0     1      Apple   AAPL  2.689903e+12   176.919492  United States
1     2  Microsoft   MSFT  2.427170e+12   326.537958  United States
2     3     NVIDIA   NVDA  2.259353e+12    92.105725  United States

In [12]:
df_eaning.head(3)

   Rank          Name   Symbol  earnings_ttm  price (GBP)        country
0     1  Saudi Aramco  2222.SR  2.283780e+11     5.505405   Saudi Arabia
1     2         Apple     AAPL  1.216250e+11   176.734336  United States
2     3     Microsoft     MSFT  1.077870e+11   326.461762  United States

In [15]:
df_p_e_ratio.head(10)

,Rank,Name,Symbol,pe_ratio_ttm,price (GBP),country
0,1,Imperial Petroleum,IMPP,0.109943,3.108797,Greece
1,2,Vertex Energy,VTNR,0.188889,0.092197,United States
2,3,Spin Master,TOY.TO,0.224758,17.414443,Canada
3,4,Performance Shipping,PSHG,0.225293,1.467916,Greece
4,5,TherapeuticsMD,TXMD,0.340956,1.280093,United States
5,6,Chimerix,CMRX,0.433204,0.684926,United States
6,7,Tingo Group,TIO,0.456954,0.525752,United States
7,8,Canacol Energy,CNE.TO,0.462276,2.005471,Canada
8,9,CR Energy,CRZK.DE,0.517095,5.083111,Germany
9,10,Vital Energy,VTLE,0.532125,20.336712,United States

In [16]:
df_revenue.head(10)

,Rank,Name,Symbol,revenue_ttm,price (GBP),country
0,1,Walmart,WMT,665035000000,61.029186,United States
1,2,Amazon,AMZN,604334000000,143.454209,United States
2,3,Saudi Aramco,2222.SR,495354806850,5.505405,Saudi Arabia
3,4,Sinopec,600028.SS,435696880608,0.748295,China
4,5,PetroChina,601857.SS,429671599508,0.969769,China
5,6,Berkshire Hathaway,BRK-B,402877000000,347.537576,United States
6,7,Apple,AAPL,385603000000,176.706906,United States
7,8,UnitedHealth,UNH,381255000000,441.487244,United States
8,9,CVS Health,CVS,363248000000,47.729174,United States
9,10,Volkswagen,VOW3.DE,350679303398,79.995895,Germany

In [29]:
new_table = df_dividend

new_table = pd.merge(new_table,df_eaning, on='Name', how='outer')
new_table = pd.merge(new_table,df_market, on='Name', how='outer')
new_table = pd.merge(new_table,df_p_e_ratio, on='Name', how='outer',suffixes=('_df1', '_rat'))
new_table = pd.merge(new_table,df_revenue, on='Name', how='outer',suffixes=('_df1', '_rev'))


# Объединение с использованием суффиксов
#result = pd.merge(df1, df2, on='Symbol', how='outer', suffixes=('_df1', '_df2'))

Параметр suffixes=('_df1', '_df2') указывает, что к именам дублирующихся столбцов из первого DataFrame будет добавлен суффикс _df1, а к именам дублирующихся столбцов из второго DataFrame — суффикс _df2. Это позволяет избежать конфликтов имен и сохранить все данные.

In [30]:
new_table

,Rank_x,Name,Symbol_x,dividend_yield_ttm,price (GBP)_x,country_x,Rank_y,Symbol_y,earnings_ttm,price (GBP)_y,...,Rank_rat,Symbol_rat,pe_ratio_ttm,price (GBP)_rat,country_rat,Rank,Symbol,revenue_ttm,price (GBP),country
0,6706,(DIA) Distribuidora Internacional de Alimentación,DIA.MC,0.0000,0.010892,Spain,9147,DIA.MC,-1.089970e+08,0.010892,...,7382,DIA.MC,-0.621711,0.010892,Spain,1335,DIA.MC,7807745770,0.010892,Spain
1,2229,(HLBank) Hong Leong Bank,5819.KL,268.6790,3.795719,Malaysia,1237,5819.KL,1.048330e+09,3.795719,...,8577,5819.KL,11.790000,3.795719,Malaysia,3980,5819.KL,1175958513,3.795719,Malaysia
2,9795,029 Group,Z29.DE,0.0000,12.496677,Germany,7526,Z29.DE,-6.217810e+06,12.496677,...,9853,Z29.DE,-115.433000,12.496677,Germany,9870,Z29.DE,0,12.496677,Germany
3,4306,1&1,1U1.DE,35.9754,11.567848,Germany,2190,1U1.DE,4.516690e+08,11.567848,...,626,1U1.DE,7.247400,11.567848,Germany,2009,1U1.DE,4446071725,11.567848,Germany
4,5620,1-800-Flowers,FLWS,0.0000,6.084251,United States,6616,FLWS,4.721000e+06,6.084251,...,5913,FLWS,-11.536200,6.084251,United States,3307,FLWS,1831421000,6.084251,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,739,ČEZ Group,CEZ.PR,574.7580,29.800408,Czech Republic,372,CEZ.PR,4.102380e+09,29.800408,...,565,CEZ.PR,6.884740,29.800408,Czech Republic,871,CEZ.PR,13392749165,29.800408,Czech Republic
9998,3366,İsdemir,ISDMR.IS,133.4360,0.884293,Turkey,2143,ISDMR.IS,4.680210e+08,0.884293,...,6700,ISDMR.IS,-38.206400,0.884293,Turkey,2225,ISDMR.IS,3811260337,0.884293,Turkey
9999,6282,İşbir Holding,ISBIR.IS,0.0000,2.336299,Turkey,7281,ISBIR.IS,-1.685470e+06,2.336299,...,6707,ISBIR.IS,-8391.710000,2.336299,Turkey,7415,ISBIR.IS,121376591,2.336299,Turkey
10000,2988,Şişecam,SISE.IS,173.0410,0.974874,Turkey,1938,SISE.IS,5.504870e+08,0.974874,...,239,SISE.IS,4.287800,0.974874,Turkey,1687,SISE.IS,5821511758,0.974874,Turkey
10001,1747,“K” Line,9107.T,333.6210,11.842154,Japan,1313,9107.T,9.734360e+08,11.842154,...,34,9107.T,1.227210,11.842154,Japan,1532,9107.T,6568116808,11.842154,Japan

In [31]:
new_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank_x              10002 non-null  int64
 1   Name                10002 non-null  object
 2   Symbol_x            10001 non-null  object
 3   dividend_yield_ttm  10002 non-null  float64
 4   price (GBP)_x       10002 non-null  float64
 5   country_x           10000 non-null  object
 6   Rank_y              10002 non-null  int64
 7   Symbol_y            10001 non-null  object
 8   earnings_ttm        10002 non-null  float64
 9   price (GBP)_y       10002 non-null  float64
 10  country_y           10000 non-null  object
 11  Rank_df1            10002 non-null  int64
 12  Symbol_df1          10001 non-null  object
 13  marketcap           10002 non-null  float64
 14  price (GBP)_df1     10002 non-null  float64
 15  country_df1         10000 non-null  object
 16  Rank_rat            10002 non-null  int64
 17  Symbol_rat          10001 non-null  object
 18  pe_ratio_ttm        10002 non-null  float64
 19  price (GBP)_rat     10002 non-null  float64
 20  country_rat         10000 non-null  object
 21  Rank                10002 non-null  int64
 22  Symbol              10001 non-null  object
 23  revenue_ttm         10002 non-null  int64
 24  price (GBP)         10002 non-null  float64
 25  country             10000 non-null  object
dtypes: float64(9), int64(6), object(11)
memory usage: 2.0+ MB

In [32]:
new_table = new_table.drop(columns=['Rank_x', 'Rank_y', 'Rank_df1','Rank_rat','Rank']) # Удаляем столбцы 'A' и 'B'

In [35]:
new_table = new_table.drop(columns=['Symbol_rat','Symbol_df1','Symbol_y','Symbol_x','country_rat','country_df1','country_y','country_x'])

In [40]:
new_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                10002 non-null  object
 1   dividend_yield_ttm  10002 non-null  float64
 2   earnings_ttm        10002 non-null  float64
 3   marketcap           10002 non-null  float64
 4   pe_ratio_ttm        10002 non-null  float64
 5   Symbol              10001 non-null  object
 6   revenue_ttm         10002 non-null  int64
 7   price (GBP)         10002 non-null  float64
 8   country             10000 non-null  object
dtypes: float64(5), int64(1), object(3)
memory usage: 703.4+ KB

In [41]:
new_table = new_table.drop(columns=['price (GBP)_rat','price (GBP)_df1','price (GBP)_y','price (GBP)_x'])

KeyError: "['price (GBP)_rat', 'price (GBP)_df1', 'price (GBP)_y', 'price (GBP)_x'] not found in axis"

In [45]:
new_table = new_table.fillna("not country")
new_table

,Name,dividend_yield_ttm,earnings_ttm,marketcap,pe_ratio_ttm,Symbol,revenue_ttm,price (GBP),country
0,(DIA) Distribuidora Internacional de Alimentación,0.0000,-1.089970e+08,6.322133e+08,-0.621711,DIA.MC,7807745770,0.010892,Spain
1,(HLBank) Hong Leong Bank,268.6790,1.048330e+09,7.920216e+09,11.790000,5819.KL,1175958513,3.795719,Malaysia
2,029 Group,0.0000,-6.217810e+06,6.248342e+07,-115.433000,Z29.DE,0,12.496677,Germany
3,1&1,35.9754,4.516690e+08,2.039417e+09,7.247400,1U1.DE,4446071725,11.567848,Germany
4,1-800-Flowers,0.0000,4.721000e+06,3.907330e+08,-11.536200,FLWS,1831421000,6.084251,United States
...,...,...,...,...,...,...,...,...,...
9997,ČEZ Group,574.7580,4.102380e+09,1.599717e+10,6.884740,CEZ.PR,13392749165,29.800408,Czech Republic
9998,İsdemir,133.4360,4.680210e+08,2.564457e+09,-38.206400,ISDMR.IS,3811260337,0.884293,Turkey
9999,İşbir Holding,0.0000,-1.685470e+06,8.453940e+07,-8391.710000,ISBIR.IS,121376591,2.336299,Turkey
10000,Şişecam,173.0410,5.504870e+08,2.986254e+09,4.287800,SISE.IS,5821511758,0.974874,Turkey
10001,“K” Line,333.6210,9.734360e+08,7.982348e+09,1.227210,9107.T,6568116808,11.842154,Japan

ТЗ для датасета


4. Отсоритруем и изучим данные
5. Удалим данные которые нам не нужны
6. Потренеруем методы из Степика для строк и int
7. Сгруппируем таблицу по разным параментрам.
8. Построим графики по разным срезам для каждым данным
9. Построим график зависимости и влияния разных метрик дрг на друга.
10. Сохраним таблицу в excel